# Generated by Django 3.2.3 on 2021-06-05 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('user_name', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=15)),
            ],
        ),
    ]
