# Generated by Django 3.2.3 on 2021-06-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0002_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=50)),
                ('admin_email', models.EmailField(max_length=254)),
                ('admin_password', models.CharField(max_length=50)),
            ],
        ),
    ]
