# Generated by Django 3.2.3 on 2021-06-09 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0005_category_adding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryadd',
            name='stock',
        ),
        migrations.AlterField(
            model_name='category_adding',
            name='stock',
            field=models.CharField(choices=[('green', 'GREEN'), ('blue', 'BLUE'), ('red', 'RED'), ('orange', 'ORANGE'), ('black', 'BLACK')], default='green', max_length=6),
        ),
    ]
