# Generated by Django 3.2.3 on 2021-06-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0007_alter_category_adding_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_cate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='img')),
                ('stock_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='category_adding',
            name='image',
            field=models.ImageField(upload_to='picture'),
        ),
    ]
