# Generated by Django 3.2.3 on 2021-06-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0008_auto_20210611_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('campaign', models.CharField(max_length=100)),
                ('image_field', models.ImageField(blank=True, null=True, upload_to='imgoffer')),
                ('stock_name', models.CharField(max_length=100)),
            ],
        ),
    ]
