# Generated by Django 3.2.3 on 2021-06-16 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0009_offers'),
    ]

    operations = [
        migrations.CreateModel(
            name='sub_cate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(max_length=100)),
                ('image_field', models.ImageField(blank=True, null=True, upload_to='imgsub')),
                ('stock_name', models.CharField(max_length=100)),
            ],
        ),
    ]
